"""Updates to user model

Revision ID: 0cbe8a227139
Revises: 3fd770a1098
Create Date: 2016-08-07 16:15:12.926844

"""

# revision identifiers, used by Alembic.
revision = '0cbe8a227139'
down_revision = '3fd770a1098'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('users', 'email')
    ### end Alembic commands ###
