"""Add role permission level attribute

Revision ID: 11b6099662d4
Revises: 4e3c0ee80932
Create Date: 2017-01-08 17:28:30.281892

"""

# revision identifiers, used by Alembic.
revision = '11b6099662d4'
down_revision = '4e3c0ee80932'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('level', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'level')
    ### end Alembic commands ###
