"""add password hash

Revision ID: 1a2ccff71da
Revises: 3fd770a1098
Create Date: 2015-12-03 21:27:20.565998

"""

# revision identifiers, used by Alembic.
revision = '1a2ccff71da'
down_revision = '3fd770a1098'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_emial', table_name='users')
    op.drop_column('users', 'emial')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('emial', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('ix_users_emial', 'users', ['emial'], unique=True)
    ### end Alembic commands ###
