"""Track last_password and password timestamp

Revision ID: 1e745461efb2
Revises: 1d66c16f620e
Create Date: 2016-10-24 08:57:14.706591

"""

# revision identifiers, used by Alembic.
revision = '1e745461efb2'
down_revision = '1d66c16f620e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_password_hash', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('password_timestamp', sa.TIMESTAMP(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_timestamp')
    op.drop_column('user', 'last_password_hash')
    ### end Alembic commands ###
