"""Add login support to user model

Revision ID: 352fba1bf15
Revises: 1a2ccff71da
Create Date: 2015-12-03 22:42:41.019468

"""

# revision identifiers, used by Alembic.
revision = '352fba1bf15'
down_revision = '1a2ccff71da'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
