"""Intial auth migration

Revision ID: f0653dcbdcc6
Revises: 3b5ab593290f
Create Date: 2016-08-09 22:53:48.755349

"""

# revision identifiers, used by Alembic.
revision = 'f0653dcbdcc6'
down_revision = '3b5ab593290f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_hash')
    ### end Alembic commands ###
