"""Create initial Patient model

Revision ID: 3b5ab593290f
Revises: 6c87193c08bf
Create Date: 2016-08-08 20:48:01.334623

"""

# revision identifiers, used by Alembic.
revision = '3b5ab593290f'
down_revision = '6c87193c08bf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('middle_initial', sa.String(length=1), nullable=True),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('address1', sa.String(length=256), nullable=True),
    sa.Column('address2', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('state', sa.String(length=2), nullable=True),
    sa.Column('zip', sa.String(length=9), nullable=True),
    sa.Column('ssn', sa.String(length=9), nullable=True),
    sa.Column('phone_mobile', sa.String(length=16), nullable=True),
    sa.Column('phone_home', sa.String(length=16), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_dob'), 'patient', ['dob'], unique=False)
    op.create_index(op.f('ix_patient_email'), 'patient', ['email'], unique=False)
    op.create_index(op.f('ix_patient_first_name'), 'patient', ['first_name'], unique=False)
    op.create_index(op.f('ix_patient_last_name'), 'patient', ['last_name'], unique=False)
    op.create_index(op.f('ix_patient_phone_mobile'), 'patient', ['phone_mobile'], unique=False)
    op.create_index(op.f('ix_patient_ssn'), 'patient', ['ssn'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_ssn'), table_name='patient')
    op.drop_index(op.f('ix_patient_phone_mobile'), table_name='patient')
    op.drop_index(op.f('ix_patient_last_name'), table_name='patient')
    op.drop_index(op.f('ix_patient_first_name'), table_name='patient')
    op.drop_index(op.f('ix_patient_email'), table_name='patient')
    op.drop_index(op.f('ix_patient_dob'), table_name='patient')
    op.drop_table('patient')
    ### end Alembic commands ###
