"""Add description to user model

Revision ID: 4e3c0ee80932
Revises: 629703e690f1
Create Date: 2017-01-03 08:40:41.867883

"""

# revision identifiers, used by Alembic.
revision = '4e3c0ee80932'
down_revision = '629703e690f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('description', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'description')
    ### end Alembic commands ###
