"""add last_seen to user model

Revision ID: 52a9e98b3105
Revises: 5ba6c286c5a8
Create Date: 2016-11-27 10:00:50.908654

"""

# revision identifiers, used by Alembic.
revision = '52a9e98b3105'
down_revision = '5ba6c286c5a8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    ### end Alembic commands ###
