"""user account management support


Revision ID: 5ba6c286c5a8
Revises: d0e4ba66e284
Create Date: 2016-10-25 00:41:29.599838

"""

# revision identifiers, used by Alembic.
revision = '5ba6c286c5a8'
down_revision = 'd0e4ba66e284'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_email', sa.String(length=128), nullable=True))
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.create_index(op.f('ix_user_last_email'), 'user', ['last_email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_email'), table_name='user')
    op.alter_column('user', 'username',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('user', 'last_email')
    ### end Alembic commands ###
