"""Add permssion model

Revision ID: 629703e690f1
Revises: 0d9ec3fc8d5e
Create Date: 2016-12-29 08:58:01.543675

"""

# revision identifiers, used by Alembic.
revision = '629703e690f1'
down_revision = '0d9ec3fc8d5e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_app_permission',
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('app_permission_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['app_permission_id'], ['app_permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_app_permission')
    op.drop_table('app_permission')
    ### end Alembic commands ###
