"""Update User model for registration and auth

Revision ID: 6facbdaf9334
Revises: d316289c5d42
Create Date: 2016-08-18 00:10:22.968292

"""

# revision identifiers, used by Alembic.
revision = '6facbdaf9334'
down_revision = 'd316289c5d42'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dob', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=16), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phone')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'dob')
    ### end Alembic commands ###
