"""Confirmation boolean added to user model

Revision ID: 7bc6255e6fad
Revises: 6facbdaf9334
Create Date: 2016-08-22 13:32:45.574113

"""

# revision identifiers, used by Alembic.
revision = '7bc6255e6fad'
down_revision = '6facbdaf9334'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'confirmed')
    ### end Alembic commands ###
